services:
  frontend:
    image: taxapp-frontend
    build:
      context: ./frontend
    ports:
      - "80:80"

  backend:
    image: taxapp-backend
    build:
      context: ./backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - orderdata:/data/db
      - configdb:/data/configdb
    command: [ --auth ]
    restart: always

volumes:
  orderdata:
  configdb:
